### PR TITLE
Add support for windows.

### PR DESCRIPTION
**Pull request by Chemiseblanc**
Normally explorer.exe always returns 1 since the built-in variable ERRORLEVEL is used for error checking. 
To correct this into the expected return code behavior the process is started through PowerShell.

### CODE REVIEW

**Comment by chrishrb** [comment]
Thank you for this PR! I refactored the code a bit and added support for windows in the README. 

One question: Does this work also in the WSL? I can‘t try it out on my own, because i only have a Mac with a Windows VM and WSL is not supported there.

**Comment by Chemiseblanc** [comment]
WSL looks like it works too. Their implementation xdg-open seems to forward things to the correct windows application.

**Comment by chrishrb** [comment]
thanks for testing! Then I will now merge this PR 👍

**Comment by xlboy** [comment]
@Chemiseblanc Why do you use `explorer.exe` here? (The final result is `powershell.exe start explorer.exe ...`)
but `explorer.exe` is `Windows Explorer`, not a browser program.
image

**Pull request merged**
